language: java

hosts:
  - TRAVIS

services:
  - postgresql

jdk:
  - oraclejdk8
  - oraclejdk11

install: mvn install -Dgpg.skip

before_script:
  - psql -c 'create database gemini_test;' -U postgres

script:
  - mvn archetype:update-local-catalog
  - >
      mvn archetype:generate -DarchetypeRepository=local -DarchetypeCatalog=local
      -DarchetypeGroupId=com.techempower -DarchetypeArtifactId=gemini-resin-archetype
      -Dpackage=foo.test -DartifactId=test-artifact-id -Dversion=1.0-SNAPSHOT
      -DmachineName=TRAVIS -DinteractiveMode=false
      -DdatabaseHost=host.docker.internal
      -DdatabaseName=gemini_test
      -DdatabaseUsername=postgres
  - cd test-artifact-id && mvn compile war:war
  - curl -sL http://caucho.com/download/resin-4.0.56.tar.gz | tar xz --strip-components=1
  - rm -rf webapps/*
  - cp target/test-artifact-id.war webapps/ROOT.war
  - ConfigurationFile="Dev.conf" java -jar lib/resin.jar console

